# Generated by Django 3.2.7 on 2021-12-15 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=50)),
                ('proveedor', models.TextField(max_length=50)),
                ('Origin', models.CharField(max_length=20)),
                ('carrier', models.TextField(max_length=50)),
                ('cntr', models.IntegerField()),
                ('bknumber', models.TextField(max_length=50)),
                ('ETD', models.CharField(max_length=10)),
                ('ETA', models.CharField(max_length=10)),
                ('comment', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='counterupd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=20)),
                ('st', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('trader', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='existing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarder', models.TextField(max_length=50)),
                ('Line', models.TextField(max_length=50)),
                ('POL', models.TextField(max_length=50)),
                ('POD', models.TextField(max_length=50)),
                ('terms', models.CharField(max_length=30)),
                ('rate', models.CharField(max_length=30)),
                ('currencyrate', models.CharField(max_length=30)),
                ('period', models.CharField(max_length=30)),
                ('contract', models.TextField(max_length=50)),
                ('additional', models.CharField(max_length=30)),
                ('currencyadd', models.CharField(max_length=30)),
                ('margin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodate', models.TextField(max_length=50)),
                ('podate', models.TextField(max_length=50)),
                ('Supplier', models.TextField(max_length=50)),
                ('client', models.TextField(max_length=50)),
                ('origincity', models.TextField(max_length=50)),
                ('origincountry', models.TextField(max_length=50)),
                ('destinationcity', models.TextField(max_length=50)),
                ('destinationcountry', models.TextField(max_length=50)),
                ('line', models.TextField(max_length=50)),
                ('forwarder', models.TextField(max_length=50)),
                ('number', models.TextField(max_length=50)),
                ('bknumber', models.TextField(max_length=50)),
                ('material', models.TextField(max_length=50)),
                ('cntr', models.CharField(max_length=20)),
                ('Tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tonsact', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min', models.CharField(max_length=20)),
                ('transaction', models.TextField(max_length=50)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marginEUR', models.TextField(max_length=50)),
                ('ETD', models.TextField(max_length=50)),
                ('ETA', models.TextField(max_length=50)),
                ('shipinstr', models.TextField(max_length=50)),
                ('Truck', models.BooleanField(default=False)),
                ('equip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('number', models.TextField(max_length=50)),
                ('cntr', models.IntegerField()),
                ('Tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=20)),
                ('spt', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.TextField(max_length=50)),
                ('country', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=50)),
                ('forwarder', models.TextField(max_length=50)),
                ('carrier', models.TextField(max_length=50)),
                ('cntr', models.IntegerField()),
                ('bknumber', models.TextField(max_length=50)),
                ('ETD', models.CharField(max_length=10)),
                ('ETA', models.CharField(max_length=10)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marginEUR', models.CharField(max_length=10)),
                ('BK', models.BooleanField(default=False)),
                ('SI', models.BooleanField(default=False)),
                ('Magic', models.BooleanField(default=False)),
                ('shipinstr', models.TextField(max_length=50)),
                ('equip', models.CharField(max_length=30)),
                ('Truck', models.BooleanField(default=False)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.po')),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bknumber', models.TextField(max_length=50)),
                ('number', models.TextField(max_length=50)),
                ('Supplier', models.TextField(max_length=50)),
                ('origincountry', models.TextField(max_length=50)),
                ('material', models.TextField(max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('comment', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='upd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=20)),
                ('st', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=50)),
                ('date', models.TextField(max_length=50)),
                ('material', models.TextField(max_length=50)),
                ('cntr', models.IntegerField()),
                ('Tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=50)),
                ('cpt', models.CharField(max_length=10)),
                ('stat', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.empresa')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.ports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=10)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Readiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proveedor', models.CharField(max_length=30)),
                ('Origin', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('number', models.TextField(max_length=50)),
                ('cntr', models.IntegerField()),
                ('Tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(max_length=50)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.po')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='po',
            name='Origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.ports'),
        ),
        migrations.AddField(
            model_name='po',
            name='Proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.empresa'),
        ),
        migrations.AddField(
            model_name='po',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.materials'),
        ),
        migrations.AddField(
            model_name='po',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.so'),
        ),
        migrations.CreateModel(
            name='MonthlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=10)),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.monthly')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=20)),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.monthly')),
            ],
        ),
        migrations.CreateModel(
            name='FinCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=20)),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.monthly')),
            ],
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=20)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=50)),
                ('seal', models.TextField(max_length=50)),
                ('bales', models.IntegerField()),
                ('gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tara', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vgm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.shipment')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimsUkr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('docs', models.BooleanField(default=False)),
                ('claimsupp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('set', models.CharField(max_length=20)),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.monthly')),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('bl', models.TextField(max_length=50)),
                ('reason', models.TextField(max_length=50)),
                ('comment', models.TextField(max_length=50)),
                ('currency', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photos', models.TextField(max_length=1000)),
                ('forwarder', models.TextField(max_length=1000)),
                ('carrier', models.TextField(max_length=1000)),
                ('picCust', models.BooleanField(default=False)),
                ('picVipa', models.BooleanField(default=False)),
                ('Sent', models.BooleanField(default=False)),
                ('settlement', models.BooleanField(default=False)),
                ('cntrs', models.IntegerField()),
                ('tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cn', models.BooleanField(default=False)),
                ('cn_currency', models.CharField(max_length=20)),
                ('cn_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dn', models.BooleanField(default=False)),
                ('dn_currency', models.CharField(max_length=20)),
                ('dn_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement_date', models.CharField(max_length=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.monthly')),
            ],
        ),
    ]
