# Generated by Django 3.2.7 on 2022-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readiness',
            name='Origin',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='readiness',
            name='Proveedor',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='readiness',
            name='comment',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='readiness',
            name='date',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='readiness',
            name='number',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='so',
            name='comment',
            field=models.TextField(max_length=100),
        ),
    ]
