# Generated by Django 3.2.7 on 2022-01-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0003_monthly_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly',
            name='link',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='link',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
