# Generated by Django 3.2.8 on 2022-02-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0008_alter_so_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='volume',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
