# Generated by Django 3.2.8 on 2022-02-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0009_alter_costs_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
